# Generated by Django 6.0.3 on 2026-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
